spring.application.name=tpoDA
spring.datasource.url=jdbc:mysql://localhost:3306/[nombre de tu base de datos]
spring.datasource.driverClassName=com.mysql.jdbc.Driver
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
application.security.jwt.secretKey=MiSuperClaveSecreta123456789012345678901234567890
application.security.jwt.expiration=3600000

#Agregar lo que esta debajo de este comentario al application.properties y completar los datos de mail y url del front
# Mail (configurar con cuenta real o usar Mailtrap para dev)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=auctionpro.tpo@gmail.com
spring.mail.password=jgmt utun uufz tohw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com


# URL base del front para armar el link del mail
app.frontend.url=http://localhost:8081

#Reenombrear este archivo como application.properties